language: node_js
node_js:
  - 0.8
  - "0.10"
before_script:
 - npm install
 - npm install istanbul coveralls
script: npm run travis-test

notifications:
webhooks:https://outlook.office.com/webhook/f4c6525c-1065-49d6-abdd-e6e86f3f617c@72f988bf-86f1-41af-91ab-2d7cd011db47/TravisCI/df5b02baaf0042248a43d6958ecc1eed/5ae8ccea-fc98-478b-9213-5e4ec50192cb
